// Seeds free-exercise-db (yuhonas/free-exercise-db, public domain) content for
// the movements the 26-week builder emits. BUILD-TIME ONLY — downloads the
// dataset + demo photos once and bundles them as local assets so the app never
// needs the network for exercise content. Run with: npm run seed:exercises
//
// Output:
//   assets/exercises/<FedbId>_{0,1}.jpg   demo photo pair per movement
//   src/data/fedb.ts                      generated content + require map
//
// Movements missing here (rucks, mobility flows, protocol lines) keep their
// hand-curated entries in src/program/exercise-library.ts. To remap a
// movement, edit NAME_TO_FEDB and re-run.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const RAW = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main';

// Exact builder movement name -> free-exercise-db id.
const NAME_TO_FEDB: Record<string, string> = {
  'Back Squat': 'Barbell_Squat',
  'Romanian Deadlift': 'Romanian_Deadlift',
  'Weighted Step-Up': 'Dumbbell_Step_Ups',
  'Standing Calf Raise': 'Standing_Calf_Raises',
  'Hanging Knee Raise': 'Hanging_Leg_Raise',
  'Weighted Pull-Up': 'Weighted_Pull_Ups',
  'Barbell Row': 'Bent_Over_Barbell_Row',
  'Single-Arm DB Row': 'One-Arm_Dumbbell_Row',
  'Face Pull': 'Face_Pull',
  'Farmer Carry': 'Farmers_Walk',
  'Front Squat': 'Front_Squat_Clean_Grip',
  'Walking Lunge': 'Bodyweight_Walking_Lunge',
  'Weighted Plank': 'Plank',
  'Overhead Press': 'Standing_Military_Press',
  'Incline DB Bench': 'Incline_Dumbbell_Press',
  'Weighted Dip': 'Parallel_Bar_Dip',
  'Pallof Press': 'Pallof_Press',
  'Weighted Sit-Up': 'Sit-Up',
  'Incline Treadmill': 'Walking_Treadmill',
};

interface FedbExercise {
  id: string;
  name: string;
  force: string | null;
  level: string;
  mechanic: string | null;
  equipment: string | null;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  images: string[];
}

const ROOT = join(import.meta.dirname, '..');
const ASSET_DIR = join(ROOT, 'assets', 'exercises');

async function main() {
  const res = await fetch(`${RAW}/dist/exercises.json`);
  if (!res.ok) throw new Error(`exercises.json fetch failed: ${res.status}`);
  const all = (await res.json()) as FedbExercise[];
  const byId = new Map(all.map((e) => [e.id, e]));

  mkdirSync(ASSET_DIR, { recursive: true });

  const entries: string[] = [];
  for (const [name, fedbId] of Object.entries(NAME_TO_FEDB)) {
    const ex = byId.get(fedbId);
    if (!ex) throw new Error(`No free-exercise-db entry '${fedbId}' (for '${name}')`);

    const imageKeys: string[] = [];
    for (let i = 0; i < Math.min(2, ex.images.length); i++) {
      const imgRes = await fetch(`${RAW}/exercises/${ex.images[i]}`);
      if (!imgRes.ok) throw new Error(`Image fetch failed for ${ex.images[i]}: ${imgRes.status}`);
      const file = `${fedbId}_${i}.jpg`;
      writeFileSync(join(ASSET_DIR, file), Buffer.from(await imgRes.arrayBuffer()));
      imageKeys.push(file);
      console.log(`  ${file}`);
    }

    const muscles = [...ex.primaryMuscles, ...ex.secondaryMuscles]
      .map((m) => m.toUpperCase())
      .join(' · ');
    const meta = [ex.equipment, ex.mechanic, ex.level]
      .filter((x): x is string => !!x)
      .map((x) => x.toUpperCase())
      .join(' · ');

    entries.push(
      `  ${JSON.stringify(name)}: {\n` +
        `    fedbId: ${JSON.stringify(fedbId)},\n` +
        `    muscles: ${JSON.stringify(muscles)},\n` +
        `    meta: ${JSON.stringify(meta)},\n` +
        `    instructions: ${JSON.stringify(ex.instructions)},\n` +
        `    images: [${imageKeys
          .map((f) => `require('../../assets/exercises/${f}')`)
          .join(', ')}],\n` +
        `  },`,
    );
  }

  const module_ = `// GENERATED by scripts/seed-exercises.ts — do not edit by hand.
// Content and photos from free-exercise-db (github.com/yuhonas/free-exercise-db,
// public domain), bundled as local assets so exercise pages work offline.

export interface FedbContent {
  fedbId: string;
  /** Small-caps muscle line: primary then secondary. */
  muscles: string;
  /** Small-caps equipment · mechanic · level line. */
  meta: string;
  /** Step-by-step execution, numbered by the UI. */
  instructions: string[];
  /** Bundled start/end demo photos. */
  images: number[];
}

export const FEDB: Record<string, FedbContent> = {
${entries.join('\n')}
};
`;
  writeFileSync(join(ROOT, 'src', 'data', 'fedb.ts'), module_);
  console.log(`Wrote src/data/fedb.ts with ${entries.length} movements.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
