-- Expedition Conditioning — initial schema.
--
-- Conventions:
--   * Client-generated uuid PKs -> every push is an idempotent upsert.
--   * updated_at is CLIENT-supplied (last-write-wins across devices); the
--     default now() only covers rows created outside the app. No trigger, or
--     it would clobber the LWW timestamps.
--   * Soft deletes via deleted_at so deletions replicate to other devices.
--   * Single user today, auth-ready by construction: user_id + RLS everywhere.

-- Program: generated by src/program/builder.ts and seeded via
-- scripts/seed-program.ts. Each re-seed inserts a new version; the app reads
-- the highest version. Completions key on workout_date, not program_day id,
-- so program edits never orphan history.

create table public.programs (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null,
  start_date date not null,
  version int not null,
  updated_at timestamptz not null default now(),
  unique (user_id, version)
);

create table public.program_days (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  program_id uuid not null references public.programs (id) on delete cascade,
  week int not null check (week between 1 and 52),
  day int not null check (day between 0 and 6), -- 0 = Sunday
  phase text not null,
  is_deload boolean not null default false,
  title text not null,
  blocks jsonb not null default '[]',
  updated_at timestamptz not null default now(),
  unique (program_id, week, day)
);

create table public.workout_completions (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  workout_date date not null,
  program_version int not null default 1,
  details jsonb not null default '{}',
  completed_at timestamptz not null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, workout_date)
);

create table public.weight_entries (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  measured_on date not null,
  weight_lbs numeric(5, 1) not null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, measured_on)
);

create table public.calorie_entries (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  logged_on date not null,
  label text,
  calories int not null,
  protein_g int,
  carbs_g int,
  fat_g int,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.earned_badges (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  badge_key text not null,
  earned_at timestamptz not null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (user_id, badge_key)
);

create table public.hike_logs (
  id uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  trail_id text,
  name text not null,
  hiked_on date not null,
  distance_mi numeric(4, 1),
  gain_ft int,
  duration_min int,
  pack_lbs numeric(4, 1),
  notes text,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- RLS: owner-only on every table.
do $$
declare t text;
begin
  foreach t in array array[
    'programs', 'program_days', 'workout_completions', 'weight_entries',
    'calorie_entries', 'earned_badges', 'hike_logs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy own_rows on public.%I for all to authenticated
       using (user_id = auth.uid()) with check (user_id = auth.uid())', t);
    -- Pull queries walk (user_id, updated_at).
    execute format('create index on public.%I (user_id, updated_at)', t);
  end loop;
end $$;
