// GENERATED by scripts/seed-exercises.ts — do not edit by hand.
// Content and photos from free-exercise-db (github.com/yuhonas/free-exercise-db,
// public domain), bundled as local assets so exercise pages work offline.

export interface FedbContent {
  fedbId: string;
  /** Small-caps muscle line: primary then secondary. */
  muscles: string;
  /** Small-caps equipment · mechanic · level line. */
  meta: string;
  /** Step-by-step execution, numbered by the UI. */
  instructions: string[];
  /** Bundled start/end demo photos. */
  images: number[];
}

export const FEDB: Record<string, FedbContent> = {
  "Back Squat": {
    fedbId: "Barbell_Squat",
    muscles: "QUADRICEPS · CALVES · GLUTES · HAMSTRINGS · LOWER BACK",
    meta: "BARBELL · COMPOUND · BEGINNER",
    instructions: ["This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.","Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.","Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).","Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.","Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Barbell_Squat_0.jpg'), require('../../assets/exercises/Barbell_Squat_1.jpg')],
  },
  "Romanian Deadlift": {
    fedbId: "Romanian_Deadlift",
    muscles: "HAMSTRINGS · CALVES · GLUTES · LOWER BACK",
    meta: "BARBELL · COMPOUND · INTERMEDIATE",
    instructions: ["Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.","Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.","Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.","Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Romanian_Deadlift_0.jpg'), require('../../assets/exercises/Romanian_Deadlift_1.jpg')],
  },
  "Weighted Step-Up": {
    fedbId: "Dumbbell_Step_Ups",
    muscles: "QUADRICEPS · CALVES · GLUTES · HAMSTRINGS",
    meta: "DUMBBELL · COMPOUND · INTERMEDIATE",
    instructions: ["Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs).","Place the right foot on the elevated platform. Step on the platform by extending the hip and the knee of your right leg. Use the heel mainly to lift the rest of your body up and place the foot of the left leg on the platform as well. Breathe out as you execute the force required to come up.","Step down with the left leg by flexing the hip and knee of the right leg as you inhale. Return to the original standing position by placing the right foot of to next to the left foot on the initial position.","Repeat with the right leg for the recommended amount of repetitions and then perform with the left leg."],
    images: [require('../../assets/exercises/Dumbbell_Step_Ups_0.jpg'), require('../../assets/exercises/Dumbbell_Step_Ups_1.jpg')],
  },
  "Standing Calf Raise": {
    fedbId: "Standing_Calf_Raises",
    muscles: "CALVES",
    meta: "MACHINE · ISOLATION · BEGINNER",
    instructions: ["Adjust the padded lever of the calf raise machine to fit your height.","Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.","Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.","Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Standing_Calf_Raises_0.jpg'), require('../../assets/exercises/Standing_Calf_Raises_1.jpg')],
  },
  "Hanging Knee Raise": {
    fedbId: "Hanging_Leg_Raise",
    muscles: "ABDOMINALS",
    meta: "BODY ONLY · ISOLATION · EXPERT",
    instructions: ["Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.","Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.","Go back slowly to the starting position as you breathe in.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Hanging_Leg_Raise_0.jpg'), require('../../assets/exercises/Hanging_Leg_Raise_1.jpg')],
  },
  "Weighted Pull-Up": {
    fedbId: "Weighted_Pull_Ups",
    muscles: "LATS · BICEPS · MIDDLE BACK",
    meta: "OTHER · COMPOUND · INTERMEDIATE",
    instructions: ["Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.","You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.","Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.","After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."],
    images: [require('../../assets/exercises/Weighted_Pull_Ups_0.jpg'), require('../../assets/exercises/Weighted_Pull_Ups_1.jpg')],
  },
  "Barbell Row": {
    fedbId: "Bent_Over_Barbell_Row",
    muscles: "MIDDLE BACK · BICEPS · LATS · SHOULDERS",
    meta: "BARBELL · COMPOUND · BEGINNER",
    instructions: ["Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.","Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.","Then inhale and slowly lower the barbell back to the starting position.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Bent_Over_Barbell_Row_0.jpg'), require('../../assets/exercises/Bent_Over_Barbell_Row_1.jpg')],
  },
  "Single-Arm DB Row": {
    fedbId: "One-Arm_Dumbbell_Row",
    muscles: "MIDDLE BACK · BICEPS · LATS · SHOULDERS",
    meta: "DUMBBELL · COMPOUND · BEGINNER",
    instructions: ["Choose a flat bench and place a dumbbell on each side of it.","Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.","Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.","Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.","Lower the resistance straight down to the starting position. Breathe in as you perform this step.","Repeat the movement for the specified amount of repetitions.","Switch sides and repeat again with the other arm."],
    images: [require('../../assets/exercises/One-Arm_Dumbbell_Row_0.jpg'), require('../../assets/exercises/One-Arm_Dumbbell_Row_1.jpg')],
  },
  "Face Pull": {
    fedbId: "Face_Pull",
    muscles: "SHOULDERS · MIDDLE BACK",
    meta: "CABLE · COMPOUND · INTERMEDIATE",
    instructions: ["Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."],
    images: [require('../../assets/exercises/Face_Pull_0.jpg'), require('../../assets/exercises/Face_Pull_1.jpg')],
  },
  "Farmer Carry": {
    fedbId: "Farmers_Walk",
    muscles: "FOREARMS · ABDOMINALS · GLUTES · HAMSTRINGS · LOWER BACK · QUADRICEPS · TRAPS",
    meta: "OTHER · COMPOUND · INTERMEDIATE",
    instructions: ["There are various implements that can be used for the farmers walk. These can also be performed with heavy dumbbells or short bars if these implements aren't available. Begin by standing between the implements.","After gripping the handles, lift them up by driving through your heels, keeping your back straight and your head up.","Walk taking short, quick steps, and don't forget to breathe. Move for a given distance, typically 50-100 feet, as fast as possible."],
    images: [require('../../assets/exercises/Farmers_Walk_0.jpg'), require('../../assets/exercises/Farmers_Walk_1.jpg')],
  },
  "Front Squat": {
    fedbId: "Front_Squat_Clean_Grip",
    muscles: "QUADRICEPS · ABDOMINALS · GLUTES · HAMSTRINGS",
    meta: "BARBELL · COMPOUND · INTERMEDIATE",
    instructions: ["To begin, first set the bar in a rack slightly below shoulder level. Rest the bar on top of the deltoids, pushing into the clavicles, and lightly touching the throat. Your hands should be in a clean grip, touching the bar only with your fingers to help keep it in position.","Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso. Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head and elbows up at all times. This will be your starting position.","Bend at the knees, sitting down between your legs. Continue down until your hamstrings are on your calves. Keep your knees aligned with your feet by consciously using your abductors to push your knees out as you squat.","Begin to raise the bar as you exhale by pushing the floor mainly with the heel or middle of your foot as you straighten the legs again and return to the starting position."],
    images: [require('../../assets/exercises/Front_Squat_Clean_Grip_0.jpg'), require('../../assets/exercises/Front_Squat_Clean_Grip_1.jpg')],
  },
  "Walking Lunge": {
    fedbId: "Bodyweight_Walking_Lunge",
    muscles: "QUADRICEPS · CALVES · GLUTES · HAMSTRINGS",
    meta: "COMPOUND · BEGINNER",
    instructions: ["Begin standing with your feet shoulder width apart and your hands on your hips.","Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.","Drive through the heel of your lead foot and extend both knees to raise yourself back up.","Step forward with your rear foot, repeating the lunge on the opposite leg."],
    images: [require('../../assets/exercises/Bodyweight_Walking_Lunge_0.jpg'), require('../../assets/exercises/Bodyweight_Walking_Lunge_1.jpg')],
  },
  "Weighted Plank": {
    fedbId: "Plank",
    muscles: "ABDOMINALS",
    meta: "BODY ONLY · ISOLATION · BEGINNER",
    instructions: ["Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.","Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."],
    images: [require('../../assets/exercises/Plank_0.jpg'), require('../../assets/exercises/Plank_1.jpg')],
  },
  "Overhead Press": {
    fedbId: "Standing_Military_Press",
    muscles: "SHOULDERS · TRICEPS",
    meta: "BARBELL · COMPOUND · BEGINNER",
    instructions: ["Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.","Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.","Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.","Lower the bar down to the collarbone slowly as you inhale.","Lift the bar back up to the starting position as you exhale.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Standing_Military_Press_0.jpg'), require('../../assets/exercises/Standing_Military_Press_1.jpg')],
  },
  "Incline DB Bench": {
    fedbId: "Incline_Dumbbell_Press",
    muscles: "CHEST · SHOULDERS · TRICEPS",
    meta: "DUMBBELL · COMPOUND · BEGINNER",
    instructions: ["Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.","Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.","Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.","Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.","Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.","Repeat the movement for the prescribed amount of repetitions.","When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells."],
    images: [require('../../assets/exercises/Incline_Dumbbell_Press_0.jpg'), require('../../assets/exercises/Incline_Dumbbell_Press_1.jpg')],
  },
  "Weighted Dip": {
    fedbId: "Parallel_Bar_Dip",
    muscles: "TRICEPS · CHEST · SHOULDERS",
    meta: "OTHER · COMPOUND · BEGINNER",
    instructions: ["Stand between a set of parallel bars. Place a hand on each bar, and then take a small jump to help you get into the starting position with your arms locked out.","Begin by flexing the elbow, lowering your body until your arms break 90 degrees. Avoid swinging, and maintain good posture throughout the descent.","Reverse the motion by extending the elbow, pushing yourself back up into the starting position.","Repeat for the desired number of repetitions."],
    images: [require('../../assets/exercises/Parallel_Bar_Dip_0.jpg'), require('../../assets/exercises/Parallel_Bar_Dip_1.jpg')],
  },
  "Pallof Press": {
    fedbId: "Pallof_Press",
    muscles: "ABDOMINALS · CHEST · SHOULDERS · TRICEPS",
    meta: "CABLE · ISOLATION · BEGINNER",
    instructions: ["Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice.","With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable.","With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position.","Press the cable away from your chest, fully extending both arms. You core should be tight and engaged.","Hold the repetition for several seconds before returning to the starting position.","At the conclusion of the set, repeat facing the other direction."],
    images: [require('../../assets/exercises/Pallof_Press_0.jpg'), require('../../assets/exercises/Pallof_Press_1.jpg')],
  },
  "Weighted Sit-Up": {
    fedbId: "Sit-Up",
    muscles: "ABDOMINALS",
    meta: "BODY ONLY · ISOLATION · BEGINNER",
    instructions: ["Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.","Place your hands behind your head and lock them together by clasping your fingers. This is the starting position.","Elevate your upper body so that it creates an imaginary V-shape with your thighs. Breathe out when performing this part of the exercise.","Once you feel the contraction for a second, lower your upper body back down to the starting position while inhaling.","Repeat for the recommended amount of repetitions."],
    images: [require('../../assets/exercises/Sit-Up_0.jpg'), require('../../assets/exercises/Sit-Up_1.jpg')],
  },
  "Incline Treadmill": {
    fedbId: "Walking_Treadmill",
    muscles: "QUADRICEPS · CALVES · GLUTES · HAMSTRINGS",
    meta: "MACHINE · BEGINNER",
    instructions: ["To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.","Treadmills offer convenience, cardiovascular benefits, and usually have less impact than walking outside. When walking, you should move at a moderate to fast pace, not a leisurely one. Being an activity of lower intensity, walking doesn't burn as many calories as some other activities, but still provides great benefit. A 150 lb person will burn about 175 calories walking 4 miles per hour for 30 minutes, compared to 450 calories running twice as fast. Maintain proper posture as you walk, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate."],
    images: [require('../../assets/exercises/Walking_Treadmill_0.jpg'), require('../../assets/exercises/Walking_Treadmill_1.jpg')],
  },
};
